plugin:
    name: 'eugene3993.sitemap::lang.plugin.name'
    description: 'eugene3993.sitemap::lang.plugin.description'
    author: Eugene3993
    icon: icon-sitemap
    homepage: ''
permissions:
    eugene3993.sitemap:
        tab: 'Sitemap'
        label: 'eugene3993.sitemap::lang.permissions.labels.sitemap'
