use_in_sitemap:
  property: use_in_sitemap
  title: eugene3993.sitemap::lang.config.use_in_sitemap
  default: false
  type: checkbox
  tab: Sitemap
  span: full

priority:
  property: priority
  title: eugene3993.sitemap::lang.config.priority
  type: dropdown
  tab: Sitemap
  span: auto
  options:
    1.0: '1.0'
    0.9: '0.9'
    0.8: '0.8'
    0.7: '0.7'
    0.6: '0.6'
    0.5: '0.5'
    0.4: '0.4'
    0.3: '0.3'
    0.2: '0.2'
    0.1: '0.1'

model_class:
  property: model_class
  title: eugene3993.sitemap::lang.config.model_class.label
  description: eugene3993.sitemap::lang.config.model_class.comment
  tab: Sitemap
  type: text
  span: auto

changefreq:
  property: changefreq
  title: eugene3993.sitemap::lang.config.changefreq
  type: dropdown
  tab: Sitemap
  span: auto
  options:
    always: 'always'
    hourly: 'hourly'
    daily: 'daily'
    weekly: 'weekly'
    monthly: 'monthly'
    yearly: 'yearly'
    never: 'never'
